keywords_removal = ["pos","www","com","des","inc","transfer","to","pos","auth","llc","from","net","point","of","sale","withdrawl","payment"]


merchant_list_map = {"shell" : "shell",
                 "atlantic" : "atlantic",
                 "plusnet" : "plusnet",
                 "zen" : "zen",
                 "virgin":"virgin",
                 "nowtv" : "now tv",
                 "nowtv" : "nowtv",
                 "sky" : "sky",
                 "hyperoptic" : "hyperoptic",
                 "PO LTD TELECOMS" : "post office broadband",
                 "trello" : "trello",
                 "box.com" : "box",
                 "superhuman" : "superhuman",
                 "linktree" : "linktree",
                 "relateiq" : "relateiq",
                 "mozy" : "mozy",
                 "hellofax" : "hellofax",
                 "fancy hands" : "fancy hands",
                 "rocket lawyer" : "rocket lawyer",
                 "desk.com" : "desk",
                 "yelpinc" : "yelp",
                 "unbounce" : "unbounce",
                 "bonsai" : "bonsai",
                 "calendly" : "calendly",
                 "balsamiq" : "balsamiq",
                 "clevvermail" : "clevvermail",
                 "airtable" : "airtable",
                 "airtable.com" : "airtable",
                 "distrokid" : "distrokid",
                 "distrokid.com" : "distrokid",
                 "about me" : "about me",
                 "zoho" : "zoho",
                 "slack" : "slack",
                 "jotform" : "jotform",
                 "gogo" : "gogo",
                 "gogoair" : "gogo",
                 "droplr" : "droplr",
                 "moz" : "moz",
                 "seomoz" : "moz",
                 "boingo" : "boingo",
                 "boingowirel" : "boingo",
                 "any.do" : "any.do",
                 "hellosign" : "hellosign",
                 "twilio" : "twilio",
                 "twilio*twilio" : "twilio",
                 "todoist" : "todoist",
                 "todoist.com" : "todoist",
                 "doist" : "doist",
                 "wordpress" : "wordpress",
                 "wpchrg.com" : "wordpress",
                 "buxfer" : "buxfer",
                 "buxfer.com" : "buxfer",
                 "facebook" : "facebook",
                 "facebookinc" : "facebook",
                 "facebk" : "facebook",
                 "www.fb.me" : "facebook",
                 "upwork" : "upwork",
                 "weebly" : "weebly",
                 "www.weebly.com" : "weebly",
                 "weebly.com" : "weebly",
                 "gett" : "gett",
                 "getty" : "getty",
                 "gettyimages.co" : "getty",
                 "vistaprint" : "vistaprint",
                 "vistaprint.com" : "vistaprint",
                 "vista" : "vista",
                 "skillshare" : "skillshare",
                 "skill" : "skill",
                 "co op" : "co-op insurance",
                 "veygo" : "veygo",
                 "ensure" : "ensure car insurance",
                 "admiral" : "admiral",
                 "admiral.com" : "admiral insurance",
                 "admiralinsurancemoto" : "admiral insurance",
                 "admiralinsuranceecomm" : "admiral insurance",
                 "sureterm" : "sureterm",
                 "ingenie" : "ingenie",
                 "spingenie" : "ingenie",
                 "insurethebox" : "insurethebox",
                 "wounded warrior" : "wounded warrior project",
                 "wnyc" : "wnyc",
                 "planned parenthood" : "planned parenthood",
                 "splc" : "southern poverty law center",
                 "american civil liberties" : "american civil liberties union",
                 "american civil liberti" : "american civil liberties union",
                 "aclu" : "american civil liberties union",
                 "wikimedia" : "wikimedia",
                 "wikimediafo" : "wikimedia",
                 "betterhelp" : "betterhelp",
                 "british red cross" : "british red cross",
                 "britishredcros" : "british red cross",
                 "britishredcross.or" : "british red cross",
                 "unison" : "unison",
                 "actblue" : "actblue",
                 "aspca" : "aspca",
                 "blue cross" : "blue cross",
                 "lola" : "lola",
                 "little caesars" : "little caesars",
                 "little peculiar lt" : "little caesars",
                 "little caesar's" : "little caesars",
                 "shippo" : "shippo",
                 "GOSHIPPO.COM" : "shippo",
                 "treehouse" : "treehouse",
                 "pressed juicery" : "pressed juicery",
                 "pressedjuicery.com" : "pressed juicery",
                 "panera bread" : "panera bread",
                 "panerabread" : "panera bread",
                 "huel" : "huel",
                 "huel.com" : "huel",
                 "japancrate.com" : "japan crate",
                 "www.japancrate.com" : "japan crate",
                 "postmates" : "postmates",
                 "httpspostmateca" : "postmates",
                 "lemonade" : "lemonade",
                 "chegg" : "chegg",
                 "lumosity" : "lumosity",
                 "lumosity.com" : "lumosity",
                 "mimo" : "mimo",
                 "coursera" : "coursera",
                 "duolingo" : "duolingo",
                 "general assembly" : "general assembly",
                 "hello code" : "hello code",
                 "summer energy" : "summer energy",
                 "veteran energy" : "veteran energy",
                 "nationwide energy" : "nationwide energy",
                 "nationwideenergy" : "nationwide energy",
                 "nationwide energ" : "nationwide energy",
                 "valley energy" : "valley energy",
                 "trieagle energy" : "trieagle energy",
                 "energyunited" : "energyunited",
                 "ENERGYUNITEDPROP" : "energyunitedprop",
                 "energy united" : "energy united",
                 "noble energy" : "noble energy",
                 "noble energy973" : "noble energy973",
                 "champion energy" : "champion energy",
                 "infuse energy" : "infuse energy",
                 "stream energy" : "stream energy",
                 "powerstream energy" : "powerstream energy",
                 "susstream energy" : "susstream energy",
                 "our energy" : "our energy",
                 "direct energy" : "direct energy",
                 "vectren energy" : "vectren energy",
                 "vectrenenergy" : "vectren energy",
                 "vectren" : "vectren energy",
                 "4change" : "4change energy",
                 "westar" : "westar energy",
                 "FlintEnergies" : "flint energy",
                 "flint energies" : "flint energy",
                 "duke energy" : "duke energy",
                 "duke-energy" : "duke energy",
                 "dukeengyprogress" : "duke energy",
                 "duke-ener866" : "duke energy",
                 "duke-ener800" : "duke energy",
                 "just energy" : "just energy",
                 "cps energy" : "cps energy",
                 "shell energy" : "shell energy",
                 "xcel energy" : "xcel energy",
                 "we energies" : "we energies",
                 "green mountain" : "green mountain",
                 "firstenergy" : "first energy",
                 "first energy" : "first energy",
                 "first ener" : "first energy",
                 "constellation" : "constellation",
                 "constellationutilpwr" : "constellationutilpwr",
                 "paymentconstellation" : "paymentconstellation",
                 "20constellation" : "20constellation",
                 "atmos" : "atmos energy",
                 "peoples energy" : "peoples energy",
                 "peco" : "peco energy",
                 "pecoenergy" : "peco energy",
                 "green network" : "green network energy",
                 "pure planet" : "pure planet",
                 "tonik" : "tonik",
                 "affect energy" : "affect energy",
                 "utilita" : "utilita",
                 "utility warehouse" : "utility warehouse",
                 "sse electricity" : "sse southern electric",
                 "southern electric" : "sse southern electric",
                 "sse southern" : "sse southern electric",
                 "spark energy" : "spark energy",
                 "sparkenergy" : "spark energy",
                 "so energy" : "so energy",
                 "octopus energy" : "octopus energy",
                 "npower" : "npower",
                 "councilandnpower" : "npower",
                 "isupplyenergy" : "isupplyenergy",
                 "isupply" : "isupplyenergy",
                 "first utility" : "first utility",
                 "1st broadband" : "first utility",
                 "edf energy" : "edf energy",
                 "ecotricity" : "ecotricity",
                 "ecotric" : "ecotricity",
                 "the renewable" : "ecotricity",
                 "e.on" : "e.on",
                 "daligas" : "daligas",
                 "bulb" : "bulb",
                 "avro" : "avro energy",
                 "disneyplus" : "disneyplus",
                 "disney plus" : "disneyplus",
                 "disney+" : "disneyplus",
                 "disneyplus35314369001" : "disneyplus",
                 "crave" : "crave",
                 "new york magazine" : "new york magazine",
                 "amznfreetime" : "amazon freetime",
                 "univision" : "univision",
                 "youtube" : "youtube",
                 "siriusxm" : "siriusxm",
                 "sirius" : "siriusxm",
                 "siriusxm.com" : "siriusxm.com",
                 "siriusxm.co" : "siriusxm.co",
                 "rhapsody" : "rhapsody",
                 "rhapsody.com" : "",
                 "napster" : "napster",
                 "tivo" : "tivo",
                 "sling" : "sling",
                 "sling.com" : "sling",
                 "hbo" : "hbo",
                 "wm direct llc internet" : "hbo",
                 "POF.COM" : "Plenty of Fish",
                 "buildbox.com" : "buildbox",
                 "ufc.tv" : "Ufc.Tv",
                 "flexjobs" : "flexjobs",
                 "flexjobs.com" : "flexjobs",
                 "cbs" : "cbs",
                 "willow" : "willow",
                 "ffnhelp" : "ffnhelp",
                 "minecraft" : "minecraft",
                 "minecraft.net" : "minecraft",
                 "viki.com" : "viki",
                 "discord" : "discord",
                 "audiobooks.com" : "audiobooks.com",
                 "memrise" : "memrise",
                 "memrise.com" : "memrise",
                 "nintendo" : "nintendo",
                 "cineworld" : "cineworld",
                 "vanity fair" : "vanity fair",
                 "skysports" : "skysports",
                 "skysports.com" : "skysports",
                 "texture" : "texture",
                 "nextissue" : "texture",
                 "badoo" : "badoo",
                 "badoo.com" : "badoo",
                 "origin" : "origin",
                 "origin.com" : "origin",
                 "oculus" : "oculus",
                 "oculus.com" : "oculus",
                 "discover" : "discover",
                 "humblebundl" : "humble bundle",
                 "humblebundle.com" : "humble bundle",
                 "humble bundle" : "humble bundle",
                 "humblebundle.c" : "humble bundle",
                 "national geographic" : "national geographic",
                 "dark sky"  : "the dark sky",
                 "gog.com" : "gog.com",
                 "gog" : "gog",
                 "economist" : "the economist",
                 "theeconomist" : "the economist",
                 "washington" : "the washington post",
                 "WASHPOST" : "the washington post",
                 "wash post" : "the washington post",
                 "washpos" : "the washington post",
                 "mlb.com" : "mlb",
                 "grindr" : "grindr",
                 "valve" : "steam",
                 "steamgames.com" : "steam",
                 "steampowered.com" : "steam",
                 "odeon" : "odeon",
                 "cosmopolitan" : "cosmopolitan",
                 "abcmouse" : "abcmouse",
                 "abcmouse com" : "abcmouse",
                 "kiwi crate" : "kiwi crate",
                 "kiwi c" : "kiwi crate",
                 "shipt" : "shipt",
                 "instacart" : "instacart",
                 "instacartinstacar" : "instacartinstacar",
                 "blue apron wine" : "blue apron wine",
                 "farm fresh to you" : "farm fresh to you",
                 "blue apron" : "blue apron",
                 "blueapron.com" : "blue apron",
                 "soylent" : "soylent",
                 "soylent.com" : "soylent",
                 "naturebox" : "naturebox",
                 "plated" : "plated",
                 "dine in fresh" : "dine in fresh",
                 "prime fresh" : "prime fresh",
                 "sightglass coffee" : "sightglass coffee",
                 "lowe" : "lowe",
                 "lowe's" : "lowe",
                 "lowes.com" : "lowe",
                 "nespresso" : "nespresso",
                 "degustabox" : "degustabox",
                 "degustabox.com" : "degustabox",
                 "crunch fitness" : "crunch fitness",
                 "crunch fit" : "crunch fitness",
                 "CRUNCH GYM": "crunch fitness",
                 "crunchessential600a" : "crunch fitness",
                 "fit4less" : "fit4less",
                 "barrys" : "barrys",
                 "barry's" : "barrys",
                 "the gym" : "the gym",
                 "fitness4less" : "fitness4less",
                 "pure gym" : "pure gym",
                 "puregym.com" : "pure gym",
                 "anytime fitness" : "anytime fitness",
                 "anytimefitness.co" : "anytimefitness.co",
                 "anytime fit" : "anytime fit",
                 "simplyhealth" : "simplyhealth",
                 "vitalityhealth" : "vitalityhealth",
                 "flyvitality.co" : "vitalityhealth",
                 "bupa" : "bupa",
                 "ymca" : "ymca",
                 "the salvation army" : "the salvation army",
                 "arlo technologies" : "arlo technologies",
                 "homeserve" : "homeserve",
                 "lemonade" : "lemonade",
                 "hiscox" : "hiscox liability insurance",
                 "rsa insurance" : "rsa insurance",
                 "royal sunalliance" : "rsa insurance",
                 "royal sun alliance" : "rsa insurance",
                 "royal&sun alliance" : "rsa insurance",
                 "protect your bubble" : "protect your bubble",
                 "protect your bubbl" : "protect your bubble",
                 "advent solutions" : "protect your bubble",
                 "assurant direct" : "protect your bubble",
                 "healthy pets" : "healthy pets",
                 "horse-insurance.co" : "horse-insurance.co",
                 "swinton" : "swinton",
                 "swinton.co.uk" : "swinton",
                 "assurantsoluti" : "assurant",
                 "assurantrenters.com" : "assurant",
                 "agi" : "assurant",
                 "assurant" : "assurant",
                 "petplan" : "petplan",
                 "pet plan" : "petplan",
                 "petplanet.co.uk" :"petplan",
                 "privilege" : "privilege insurance",
                 "hastings insurance" : "hastings insurance",
                 "4909hastings insur" : "hastings insurance",
                 "axa" : "axa",
                 "animal friends" : "animal friends insurance",
                 "policy expert" : "policy expert",
                 "aa" : "aa insurance",
                 "hastings direct" : "hastings direct",
                 "one call" : "once call insurance",
                 "policywise.co." : "policywise",
                 "policywise.co.uk" : "policywise",
                 "elephant" : "elephant",
                 "elephant.co.uk" : "elephant",
                 "go skippy" : "go skippy",
                 "twine" : "twine",
                 "betterment" : "betterment",
                 "acorns" : "acorns",
                 "e trade" : "e*trade",
                 "stash" : "stash",
                 "wealthfront" : "wealthfront",
                 "110519wealthfront" : "wealthfront",
                 "robinhood" : "robinhood",
                 "fidelity" : "fidelity",
                 "fid" : "fifidelity",
                 "plum" : "plum",
                 "nutmeg" : "nutmeg",
                 "nutmeg.com" : "nutmeg",
                 "wealthsimple" : "wealthsimple",
                 "etoro" : "etoro",
                 "coinbase" : "coinbase",
                 "coinbase.com" : "coinbase",
                 "cb payments" : "coinbase",
                 "moneybox" : "moneybox",
                 "vanguard" : "vanguard",
                 "cleo" : "cleo",
                 "beagle" : "beagle street",
                 "lv life" : "lv=life insurance",
                 "liverpool victoria" : "lv=life insurance",
                 "aviva" : "aviva life",
                 "vitality" : "vitality life",
                 "royal london" : "royal london",
                 "ryl london" : "royal london",
                 "onefamily" : "onefamily",
                 "family equity plan" : "onefamily",
                 "canada life" : "canada life",
                 "aig" : "aig life",
                 "santander" : "santander loans",
                 "vodafone" : "vodafone",
                 "vodafone.co.uk" : "vodafone",
                 "giffgaff" : "giffgaff",
                 "giffgaff.com" : "giffgaff",
                 "fitbit" : "fitbit",
                 "cheers health" : "cheers health",
                 "idaho fitness" : "idaho fitness",
                 "goodlife" : "goodlife fitness",
                 "whoop" : "whoop",
                 "manscaped" : "manscaped",
                 "squatch" : "dr squatch",
                 "banfield" : "banfield pet hospital",
                 "curology" : "curology",
                 "equinox" : "equinox",
                 "ipsy" : "ipsy",
                 "billie" : "billie",
                 "mission cliffs" : "mission cliffs",
                 "daily burn" : "daily burn",
                 "dailyburn" : "daily burn",
                 "soma water" : "soma water",
                 "orangetheory" : "orangetheory fitness",
                 "orangetheoryisling" : "orangetheory fitness",
                 "orangetheoryis" : "orangetheory fitness",
                 "herbalife" : "herbalife",
                 "tiege hanley" : "tiege hanley",
                 "planet fitness" : "planet fitness",
                 "planet fit" : "planet fitness",
                 "quip" : "quip",
                 "golds gym" : "golds gym",
                 "gold's gym" : "golds gym",
                 "esalon" : "esalon",
                 "esalon.com" : "esalon",
                 "lose it" : "lose it and love it",
                 "practice plan" : "practice plan",
                 "practiceplan" : "practice plan",
                 "24 hour" : "24 hour fitness",
                 "24hour" : "24 hour fitness",
                 "focusatwill.com" : "focusatwill",
                 "brain.fm" : "brain.fm",
                 "brain fm" : "brain.fm",
                 "move gb" : "movegb",
                 "movegb.com" : "movegb",
                 "myfitnesspal" : "myfitnesspal",
                 "eatthismuc" : "eat this much",
                 "eatthismuch.com" : "eat this much",
                 "proactiv" : "proactiv",
                 "proactiv.com" : "proactiv",
                 "soulcycle" : "soulcycle",
                 "calm" : "calm",
                 "calm.com" : "calm",
                 "david lloyd" : "david lloyd",
                 "david lloyds" : "david lloyd",
                 "cvs pharmacy" : "cvs pharmacy",
                 "specsavers" : "specsavers",
                 "curve subscriptionlondon" : "curve black/metal",
                 "vxnbill.com" : "vxnbill",
                 "upmc health" : "upmc health",
                 "digit.co" : "digit",
                 "digit.cosubscriptn" : "digit",
                 "digit.cowithdrawalsubscriptn" : "digit",
                 "american amicabl" : "american-amicable",
                 "american electric" : "american electric",
                 "portland water" : "portland water",
                 "lee county" : "lee county utilities",
                 "lee county elect" : "lee county electric",
                 "lee county electric" : "lee county electric",
                 "sandiego water" : "city of san diego water",
                 "southern connecticut gas" : "southern connecticut gas",
                 "oklahoma natural gas" : "oklahoma natural gas",
                 "georgia power" : "georgia power",
                 "public mobile" : "public mobile",
                 "empower" : "empower",
                 "fidelity life" : "fidelity life",
                 "cfw water" : "fort worth water",
                 "gas south" : "gas south",
                 "ladder life" : "ladder life insurance",
                 "ladderlife" : "ladder life insurance",
                 "brandless" : "brandless",
                 "brandless.com" : "brandless",
                 "citymapper" : "citymapper",
                 "monzo" : "monzo",
                 "nationwide life" : "nationwide life insurance",
                 "hydro one" : "hydro one",
                 "start ca" : "start.ca",
                 "root insurance" : "root insurance",
                 "sonnet" : "sonnet insurance",
                 "fido" : "fido mobile",
                 "economical" : "economical",
                 "enbridge" : "enbridge gas",
                 "calwater" : "calwater",
                 "erie" : "erie insurance",
                 "protective life" : "protective life insurance",
                 "consumers energy" : "consumers energy energybill",
                 "gerber life" : "gerger life insurance",
                 "juul" : "juul",
                 "pandora" : "pandora",
                 "visible" : "visible",
                 "square one" : "square one",
                 "albert genius" : "albert genius",
                 "clarity money" : "clarity money",
                 "synchrony" : "synchrony bank",
                 "apple cash" : "apple cash",
                 "applecard" : "apple card",
                 "qoins" : "qoins",
                 "nadine west" : "nadine west",
                 "shaw cable" : "shaw communications",
                 "shaw cablesystems" : "shaw communications",
                 "moneylion" : "moneylion",
                 "tucson electric" : "tucson electric",
                 "tucsonelecez" : "tucson electric",
                 "bell mobility" : "bell mobility",
                 "qapital" : "qapital",
                 "zebit" : "zebit",
                 "earninactivehour" : "earnin",
                 "earnin" : "earnin",
                 "clearme.com" : "clearme",
                 "koodo mobile" : "koodo mobile",
                 "turbotax" : "turbotax",
                 "intuit" : "turbotax",
                 "telus" : "telus",
                 "union gas" : "union gas",
                 "td insurance" : "td insurance",
                 "venmo" : "venmo",
                 "zirtual" : "zirtual",
                 "youmail" : "youmail",
                 "youfit" : "youfit health club",
                 "xsport" : "xsport",
                 "xfinity" : "xfinity mobile",
                 "wow!" : "wow! internet",
                 "windhaven" : "windhaven insurance",
                 "windstream" : "windstream",
                 "whitepages" : "whitepages",
                 "whoeasy" : "whoeasy",
                 "whoeasy.com" :"whoeasy",
                 "webpass" : "webpass",
                 "webflow.com" : "webflow",
                 "washington gas" : "washington gas",
                 "verizon" : "verizon",
                 "verizonrecurring" : "verizon",
                 "vetsource" : "vetsource",
                 "vasa fitness" : "vasa fitness",
                 "acceptvasafit" : "vasa fitness",
                 "vasafit" : "vasa fitness",
                 "usps po boxes" : "usps po boxes",
                 "usa for unhcr" : "usa for unhcr",
                 "usaa insurance" : "usaa insurance",
                 "urbansitter" : "urbansitter",
                 "upstart" : "upstart",
                 "uas" : "university accounting service",
                 "united power" : "united power",
                 "ufcgym" : "ufcgym",
                 "unitedhealthcare" : "unitedhealthcare",
                 "ugi" : "ugi utilities",
                 "ugiutilities" : "ugi utilities",
                 "txu" : "txu energy",
                 "uberconference" : "uberconference",
                 "tunein.com" : "tunein",
                 "trthfdr" : "truthfinder",
                 "truthfinder" : "truthfinder",
                 "trupanion" : "trupanion",
                 "truebill" : "truebill",
                 "trugreen" : "trugreen",
                 "trubrain" : "trubrain",
                 "trinity valley" : "trinity valley electric",
                 "trendy butler" : "trendy butler",
                 "transamerica" : "transamerica insurance",
                 "transpremierlife" : "transamerica insurance",
                 "transunion" : "transunion",
                 "ting.com" : "ting",
                 "ting" : "ting",
                 "ting-inv" : "ting",
                 "threadbeast" : "threadbeast",
                 "thrivemarketgoods" : "thrive market",
                 "thrive market" : "thrive market",
                 "thrivemarketyearlyfee" : "thrive market",
                 "nounproject.com" : "nounproject",
                 "the joint" : "the joint chiropractic",
                 "theladders.com" : "the ladders",
                 "the honest" : "the honest company",
                 "the athletic" : "the athletic",
                 "theathletic.com" : "the athletic",
                 "teensafe" : "teen safe",
                 "terminix" : "terminix",
                 "tmx" : "terminix",
                 "svcgs.com" : "svcgs",
                 "sun tan city" : "sun tan city",
                 "suddenlink" : "suddenlink",
                 "sun basket" : "sun basket",
                 "sunbasket.com" : "sun basket",
                 "straighttalk" : "straighttalk",
                 "straight talk" : "straight talk",
                 "streak.com" : "streak",
                 "stitch fix" : "stitch fix",
                 "st jude" : "st jude",
                 "stamps.com" : "stamps.com",
                 "srp" : "srp",
                 "salt rvr" : "srp",
                 "squaretrade" : "squaretrade",
                 "spokeo" : "spokeo",
                 "splendies.com" : "splendies",
                 "sonic" : "sonic",
                 "sonic.net" : "sonic",
                 "so cal gas" : "so cal gas",
                 "snackcrate.com" : "snackcrate",
                 "smiledirectclub" : "smile direct club",
                 "smartcredit.com" : "smart credit",
                 "singlesswag" : "singlesswag",
                 "simplisafe" : "simplisafe",
                 "simplisafe.com" : "simplisafe",
                 "www.simplisafe.com" : "simplesafe",
                 "sittercity" : "sittercity",
                 "sittercity.com" : "sittercity",
                 "shoedazzle.com" : "shoedazzle",
                 "shoedazzle" : "shoedazzle",
                 "shippingeasy.com" : "shippingeasy",
                 "scoresense.com" : "Score sense",
                 "scoresense" : "score sense",
                 "scana energy" : "scana energy",
                 "scanaenergy" : "scana energy",
                 "scanaenergypayment" : "scana energy",
                 "scanaenergypay" : "scana energy",
                 "scentbird" : "scent bird",
                 "www.scentbird.com" : "scent bird",
                 "scentbirdsubscription" : "scent bird",
                 "scentbird.com" : "scent bird",
                 "scentbirdsubscript" : "scent bird",
                 "sanantonio water" : "san antonio water system",
                 "san antonio water system" : "san antonio water system",
                 "safeco" : "safeco insurance",
                 "safecart" : "safecart",
                 "safecart.com" : "safecart",
                 "roku" : "roku",
                 "rocksbox": "rocksbox",
                 "rochester gas" : "rochester gas and electric",
                 "rochestergas" : "rochester gas and electric",
                 "roch gas" : "rochester gas and electric",
                 "resumenow" : "resume now",
                 "retro fitness" : "retro fitness",
                 "republic services" : "republic services",
                 "rent the runway" : "rent the runway",
                 "reliant energy" : "reliant energy",
                 "redbox" : "redbox",
                 "radiotopi" : "radiotopi",
                 "questar gas" : "questar gas",
                 "questargas" : "questar gas",
                 "puget sound" : "puget sound energy",
                 "pseg" : "pseg",
                 "psegli" : "pseg",
                 "prodigygame.com" : "prodigy game",
                 "progressive" : "progressive insurance",
                 "united fin cas" : "progressive insurance",
                 "prog direct ins" : "progressive insurance",
                 "ppl electric" : "ppl electric",
                 "ppl electr" : "ppl electr",
                 "primerica" : "primerica",
                 "portland general" : "portland general electric",
                 "portland gnl" : "portland general electric",
                 "portland generalpayment" : "portland general electric",
                 "plexus" : "plexus worldwide",
                 "plexusworldwide" : "plexus worldwide",
                 "planet beach" : "planet beach",
                 "pgande" : "pacific gas and electric",
                 "pg e" : "pacific gas and electric",
                 "peoples gas" : "peoples gas",
                 "peoplefinders" : "people finders",
                 "penn mutual" : "penn mutual life insurance",
                 "pennymac" : "pennymac",
                 "peoplesmart.com" : "poeple smart",
                 "persopo.com" : "persopo",
                 "philadelphia gas" : "philadelphia gas works",
                 "pgw" : "philadelphia gas works",
                 "pdffiller.com" : "pdffiller",
                 "peloton" : "peloton",
                 "penn national" : "penn national insurance",
                 "penn nat'l" : "penn national insurance",
                 "pacific power" : "pacific power",
                 "oscar insurance" : "oscar insurance",
                 "oscarinsuranceco" : "oscar insurance",
                 "oscarinsuranceoh" : "oscar insurance",
                 "oscarinsurancetx" : "oscar insurance",
                 "optimum" : "optimum cable",
                 "cablevision" : "optimum cable",
                 "orkin" : "orkin",
                 "orange county" : "orange county utility",
                 "ooma" : "ooma",
                 "ooma.com" : "ooma",
                 "www.ooma.com" : "ooma",
                 "onstar" : "onstar",
                 "one medical" : "one medical",
                 "nv energy" : "nv energy",
                 "onedrive" : "onedrive",
                 "oklahoma gas electric" : "oklahoma gas & electric",
                 "nutri system" : "nutri system",
                 "north shore gas" : "north shore gas",
                 "novec" : "northern virginia electric cooperative",
                 "northwestern" : "northwestern energy",
                 "nw energy" : "northwestern energy",
                 "norton" : "norton",
                 "northwestern mutual" : "northwestern mutual",
                 "nfhsnetwork.com" : "nfhs network",
                 "nicor" : "nicor gas",
                 "new york life" : "new york life insurance",
                 "nylife" : "new york life insurance",
                 "newyorklife" : "new york life insurance",
                 "nba league pass" : "nba league pass",
                 "navient" : "navient",
                 "navi ed" : "navient",
                 "nationwide pet" : "nationwide pet insurance",
                 "nashville elect" : "nashville electric service",
                 "nes" : "nashville electric service",
                 "nashville electric" : "nashville electric service",
                 "myperfresume" : "my perfect resume",
                 "myperfresume855" : "my perfect resume",
                 "myheritage" : "my heritage",
                 "myheritageltd" : "my heritage",
                 "myfico" : "myfico",
                 "myfico.com" : "myfico",
                 "myfax" : "myfax",
                 "munchpak.com" : "munchpack",
                 "munchpak.comsnacks" : "munchpack",
                 "morningstar" : "morningstar",
                 "moviepass" : "moviepass",
                 "mixpanel" : "mixpanel",
                 "monitronics" : "monitronics",
                 "mister car wash" : "mister car wash",
                 "mint creditmonitor" : "mint credit monitor",
                 "metromile" : "metromile",
                 "metropolitan" : "metropolitan utilities",
                 "metropcs" : "metropcs",
                 "midamerican" : "midamerican energy",
                 "midamericanutili888" : "midamerican energy",
                 "mercury" : "mercury insurance",
                 "massage heights" : "massage heights",
                 "maui electric" : "maui electric",
                 "massmutual" : "massmutual",
                 "massage envy" : "massage envy",
                 "mapfre" : "mapfre insurance",
                 "commerce ins" : "mapfre insurance",
                 "commerce insurance" : "mapfre insurance",
                 "commerce insurea" : "mapfre insurance",
                 "lucid software" : "lucid software",
                 "loudoun water" : "loudoun water",
                 "life time" : "life time fitness",
                 "lifetimefitness.com" : "life time fitness",
                 "le tote" : "le tote",
                 "lifelock" : "lifelock",
                 "lifeloc" : "lifelock",
                 "liberty utilities" : "liberty utilities",
                 "liberty utilit" : "liberty utilities",
                 "libertyutilities" : "liberty utilities",
                 "liberty mutual" : "liberty mutual",
                 "legalzoom.com" : "legalzoom",
                 "legalzoom" : "legalzoom",
                 "legalshield" : "legalshield",
                 "lvvwd" : "las vegas valley water district",
                 "la times" : "la times",
                 "lat" : "la times",
                 "los angeles times" : "la times",
                 "leetcode.com" : "leet code",
                 "la fitness" : "la fitness",
                 "l a fitness" : "la fitness",
                 "kaiser" : "kaiser health",
                 "julep beauty" : "julep beauty",
                 "jackson electric" : "jackson electrics",
                 "jackson electrics" : "jackson electrics",
                 "jackson electricalb913rl" : "jackson electrics",
                 "ipage" : "ipage",
                 "iphone citiz" : "iphone upgrade program",
                 "iphone citizensoneloan" : "iphone upgrade program",
                 "iphone citizloan" : "iphone upgrade program",
                 "intelius.com" : "intelius",
                 "intermountain" : "intermountain gas",
                 "integral life" : "integral life",
                 "imperfect produce" : "imperfect produce",
                 "imperfect foods" : "imperfect produce",
                 "imdb" : "imdbpro",
                 "readyrefresh" : "ready refresh",
                 "spring nestle pure" : "ready refresh",
                 "identityiq.com" : "identityiq",
                 "hum nutrition" : "hum nutrition",
                 "humana" : "humana",
                 "hotstar" : "hotstar",
                 "hp instant ink" : "hp instant ink",
                 "hootsuite" : "hootsuite",
                 "home chef" : "home chef",
                 "hgtv" : "hgtv",
                 "healthy paws pet" : "healthy paws pet insurance",
                 "hanover" : "hanover insurance",
                 "hand and stone" : "hand and stone",
                 "hairstory" : "hairstory",
                 "hallmark" : "hallmark",
                 "gwinnett county" : "gwinnett county water",
                 "greenville water" : "greenville water",
                 "grayson collin" : "grayson collin electric cooperative",
                 "golden state" : "golden state water",
                 "goldenstatewater" : "golden state water",
                 "globe life" : "globe life insurance",
                 "globalfit" : "globalfit",
                 "gexa energy" : "gexa energy",
                 "geeksquad" : "geek squad plan",
                 "geek squad plan" : "geek squad plan",
                 "geeksquadplan" : "geek squad plan",
                 "fye backstage" : "fye backstage pass",
                 "frontier utilities" : "frontier utilities",
                 "frontier utilitie" : "frontier utilities",
                 "frontier utiliti" : "frontier utilities",
                 "frontier utilit" : "frontier utilities",
                 "frontier" : "frontier",
                 "freshpatch.com" : "fresh patch",
                 "www.freshpatch.com" : "fresh patch",
                 "freedom mobile" : "freedom mobile",
                 "fragrant jewels" : "fragrant jewels",
                 "formswift.com" : "swift",
                 "foot cardigan" : "foot cardigan",
                 "fitness sf" : "fitness sf",
                 "fitness sffillmore" : "fitness sf",
                 "five four club" : "five four club",
                 "fivefourclub.com" : "five four club",
                 "fitness 19" : "fitness 19",
                 "fitness connecti" : "fitness connection",
                 "filethis" : "filethis",
                 "air filters" : "filter easy",
                 "fastrak" : "fastrak",
                 "farmers insurance" : "farmers insurance",
                 "farmers ins" : "farmers insurance",
                 "fabfitfun" : "fabfitfun",
                 "express scripts" : "express scripts pharmacy",
                 "esi" : "express scripts pharmacy",
                 "eversource" : "eversource",
                 "evoice" : "evoice",
                 "epoch.com" : "epoch payment solutions",
                 "espn plus" : "espn+",
                 "erenterplan" : "erenterplan",
                 "erenterplan.com" : "erenterplan",
                 "entergy" : "entergy",
                 "embrace pet" : "embrace pet insurance",
                 "empirestore.net" : "empire store",
                 "elizabethton" : "elizabethton electric",
                 "elysium health" : "elysium health",
                 "emwd" : "eastern municipal water district",
                 "ebmud" : "east bay municipal utility district",
                 "disney books" : "early moments",
                 "dte energy" : "dte energy",
                 "dropmark" : "dropmark",
                 "doctors w/o border" : "doctors without borders",
                 "doctors w/o borders" : "doctors without borders",
                 "dixie electric" : "dixie electric",
                 "dis" : "disneyland annual passport",
                 "directv" : "directv",
                 "disney movie" : "disney movie club",
                 "disney movie800" : "disney movie club",
                 "dish" : "dish network",
                 "nitromonthly" : "discord nitro",
                 "discount power" : "discount power",
                 "dialpad" : "dialpad",
                 "delta sonic" : "delta sonic car wash",
                 "delmarva" : "delmarva power",
                 "delmarvapower" : "delmarva power",
                 "dave" : "dave",
                 "dave.com" : "dave",
                 "dave" : "dave",
                 "curlbox" : "curlbox",
                 "culligan water" : "culligan water of los angeles",
                 "paymentculligan" : "culligan water of los angeles",
                 "cubesmart" : "cube smart",
                 "crew carwash" : "crew carwash",
                 "credit sesame" : "credit sesame",
                 "cox" : "cox communications",
                 "course hero" : "course hero",
                 "coursehero.com" : "course hero",
                 "cozy" : "cozy",
                 "coopers hawk" : "cooper's hawk winery",
                 "connexus" : "connexus energy",
                 "consumer cellular" : "consumer cellular",
                 "commonwealth edison" : "commonwealth edison",
                 "comed util_bil" : "commonwealth edison",
                 "college sports live" : "college sports live",
                 "columbia gas" : "columbia gas",
                 "cobb county water" : "cobb county water",
                 "cobb emc" : "cobb electric membership",
                 "classmates" : "classmates",
                 "classmates.com" : "classmates",
                 "clean freak car wash" : "clean freak car wash",
                 "santa clara" : "santa clara utilities",
                 "city of austin utilities" : "city of austin utilities",
                 "raleigh utility" : "raleigh utility",
                 "raleigh util" : "raleigh utility",
                 "modesto utilit" : "modesto utility",
                 "modesto util" : "modesto utility",
                 "cinemark theatres" : "cinemark theatres",
                 "citizens energy group" : "citizens energy group",
                 "citizensenergygrouppmt" : "citizens energy group",
                 "citizensenergyg": "citizens energy group",
                 "citizensenergy" : "citizens energy group",
                 "chewy.com" : "chewy.com",
                 "chewy" : "chewy.com",
                 "charter" : "charter spectrum",
                 "central maine power" : "central maine power",
                 "centerpoint energy" : "centerpoint energy",
                 "cpenergy" : "cpenergy",
                 "carefirst" : "carefirst",
                 "cable one" : "cable one",
                 "burst oral care" : "burst oral care",
                 "careburstora" : "burst oral care",
                 "bright house" : "bright house networks",
                 "brightcellars" : "bright cellars",
                 "brightcellars.com" : "bright cellars",
                 "boston globe" : "boston globe",
                 "www.boxycharm.com" : "boxycharm",
                 "boxycharm" : "boxycharm",
                 "boxycharm.com" : "boxycharm",
                 "bridgecrest" : "bridgecrest",
                 "boost mobile" : "boost mobile",
                 "blue mountain" : "blue mountain",
                 "bluemountain" : "blue mountain",
                 "bluemountain.com" : "blue mountain",
                 "bluemountainpe" : "blue mountain",
                 "bluemountainyard" : "blue mountain",
                 "blink moto" : "blink fitness",
                 "blink web" : "blink fitness",
                 "black hills" : "black hills energy",
                 "biggerpockets.com" : "bigger pckets",
                 "bge" : "bge",
                 "berkeley electric" : "berkeley electric cooperative",
                 "berkeley electri" : "berkeley electric cooperative",
                 "berkeley elect" : "berkeley electric cooperative",
                 "bevel" : "bevel",
                 "beenverified.com" : "beenverified",
                 "beenverified" : "beenverified",
                 "beenverifie" : "beenverified",
                 "barkbox" : "barkbox",
                 "barkbox.com" : "barkbox",
                 "bark co" : "barkbox",
                 "banfield" : "banfield wellness plan",
                 "authorize.net" : "authorize.net",
                 "austin utilities" : "austin utilities",
                 "att" : "at&t",
                 "at&t" : "at&t",
                 "atlanta journal constitutio" : "atlanta journal constitution",
                 "atlantic city electric" : "atlantic city electric",
                 "atlantic city el" : "atlantic city electric",
                 "atlantic city elec" : "atlantic city electric",
                 "archives.com" : "archives",
                 "az rep" : "arizona republic",
                 "anthem" : "anthem health insurance",
                 "animoto" : "animoto",
                 "animal jam" : "animal jam",
                 "www.animaljam.com" : "animal jam",
                 "animaljam.com" : "animal jam",
                 "ana enterprise" : "ana enterprise",
                 "amica" : "amica insurance",
                 "ameriprise" : "ameriprise insurance",
                 "american utility" : "american utility",
                 "electronic aum" : "american utility",
                 "american-water" : "american water",
                 "american water" : "american water",
                 "american greetings" : "american greetings",
                 "amazon" : "amazon",
                 "allure beauty box" : "allure beauty box",
                 "alliant" : "alliant energy",
                 "alameda county" : "alameda county utility",
                 "alabama pow" : "alabama power",
                 "allstate" : "allstate",
                 "affirm" : "affirm",
                 "affirm.com" : "affirm",
                 "aiga" : "aiga",
                 "adyen" : "adyen",
                 "adobe" : "adobe",
                 "adore me" : "adore me",
                 "acorn tv" : "acorn tv",
                 "acorn.tv" : "acorn tv",
                 "aaa ncnu" : "aaa ncnu",
                 "aaa insurance" : "aaa insurance",
                 "123helpme" : "123helpme",
                 "15five" : "15five",
                 "time warner" : "time warner",
                 "project fi" : "project fi",
                 "comcast" : "comcast",
                 "microsoft" : "microsoft",
                 "msft" : "microsoft",
                 "google storage" : "google storage",
                 "google st" : "google storage",
                 "google storg" : "google storage",
                 "google stor" : "google storage",
                 "google storgoogle" : "google storage",
                 "google stor855" : "google storage",
                 "gogoair" : "gogoair",
                 "gogoair.c" : "gogoair",
                 "adt" : "adt security",
                 "adtsecurity" : "adt security",
                 "centurylink" : "centurylink",
                 "centurylinkconvctrconc" : "centurylink",
                 "centurylinkconvcseattle" : "centurylink",
                 "american home shield" : "american home shield",
                 "home warranty" : "american home shield",
                 "american hm" : "american home shield",
                 "angie's" : "angie's list",
                 "angies" : "angie's list",
                 "equifax" : "equifax",
                 "experian" : "experian",
                 "identity guard" : "identity guard",
                 "identityguard.com" : "identity guard",
                 "credit defense" : "defense platinum",
                 "youtube" : "youtube premium",
                 "youtubepre" : "youtube premium",
                 "youtubepremium" : "youtube premium",
                 "intuit" : "intuit",
                 "quickbooks" : "intuit",
                 "lexington law" : "lexington law",
                 "godaddy" : "godaddy",
                 "godaddy.com" : "godaddy",
                 "goda" : "godaddy",
                 "kindle" : "amazon kindle",
                 "google domains" : "google domains",
                 "amazon music" : "amazon music",
                 "cash app" : "cash app",
                 "square cash" : "cash app",
                 "square inc" : "cash app",
                 "zurich assurance" : "zurich assurance",
                 "liberated syndication" : "lbsyn",
                 "american family" : "american family insurance",
                 "gamefly" : "gamefly",
                 "gamefly.com" : "gamefly",
                 "ringcentral" : "ringcentral",
                 "bpmsupreme.com" : "bpm supreme",
                 "freeshipping.com" : "freeshipping.com",
                 "vinyl me" : "vinyl me",
                 "vinylmeplease" : "vinyl me",
                 "san diego gas" : "san diego gas and electric",
                 "san diego gaso" : "san diego gas and electric",
                 "sdg e" : "san diego gas and electric",
                 "zillow" : "zillow",
                 "zillow.com" : "zillow",
                 "florida power" : "florida power & electric",
                 "fpl" : "florida power & electric",
                 "vidiq.com" : "vidiq",
                 "2checkout.com" : "2checkout",
                 "2co.com" : "2checkout",
                 "instapaper" : "instapaper",
                 "metlife" : "metlife",
                 "metlifecon" : "metlife",
                 "metlifecl" : "metlife",
                 "metlifertl" : "metlife",
                 "infusionsoft" : "infusionsoft",
                 "sprint" : "sprint",
                 "sprint8006396111" : "sprint",
                 "new york times" : "new york times",
                 "newyorktim" : "new york times",
                 "news times" : "new york times",
                 "newyorktime" : "new york times",
                 "the new york" : "new york times",
                 "new yorker" : "the new yorker",
                 "esurance" : "esurance",
                 "help.jagex.com" : "jagex",
                 "jagex.com" : "jagex",
                 "public storage" : "public storage",
                 "rogers": "rogers",
                 "rocky mountain" : "rocky mountain power",
                 "rockymtn" : "rocky mountain power",
                 "notion" : "notion",
                 "notion.so" : "notion",
                 "network for good" : "network for good",
                 "smallpdf" : "smallpdf",
                 "splice.com" : "splice",
                 "splice" : "splice",
                 "1and1.com" : "1&1 internet",
                 "www.1and1.com" : "1&1 internet",
                 "harvard business" : "harvard business review",
                 "avatar nutrition" : "avatar nutrition",
                 "venngage.com" : "venngage",
                 "semrush" : "semrush",
                 "semrush.com" : "semrush",
                 "www.semrush.com" : "semrush",
                 "wallet" : "wallethub",
                 "lookout" : "lookout",
                 "extra space storage" : "extra space storage",
                 "instant checkmate" : "instant checkmate",
                 "instantcheckma" : "instant checkmate",
                 "instantchec" : "instant checkmate",
                 "instant imaging" : "instant checkmate",
                 "nstantcheckmate.com" : "instant checkmate",
                 "instantcheckmate." : "instant checkmate",
                 "six flags" : "six flags",
                 "dr frights" : "dr frights",
                 "giganews" : "giganews",
                 "funimation" : "funimation",
                 "funimation.com" : "funimation",
                 "mileiq" : "mileiq",
                 "talkspace" : "talkspace",
                 "smule" : "smule",
                 "sharefile" : "citrix sharefile",
                 "247sports.com" : "247sports",
                 "sport & recreation" : "247sports",
                 "torguard" : "torguard",
                 "t-mobile" : "t-mobile",
                 "tmobile" : "t-mobile",
                 "t-mobile.com" : "t-mobile",
                 "tmobile.com" : "t-mobile",
                 "hughesnet" : "hughesnet",
                 "hughesnet.com" : "hughesnet",
                 "hughesnet.c" : "hughesnet",
                 "hughesnet.co" : "hughesnet",
                 "audible.co.uk" : "audible",
                 "audible" : "audible",
                 "match.com" : "match.com",
                 "twitch" : "twitch",
                 "twitchtv" : "twitch",
                 "verizon" : "verizon",
                 "vzwrlss" : "verizon",
                 "vzw" : "verizon",
                 "inmotionhosting.com" : "inmotion hosting",
                 "austin energy" : "austin energy",
                 "austin_energy" : "austin energy",
                 "languagepod101" : "languagepod101",
                 "babbel" : "babbel",
                 "babbel.com" : "babbel",
                 "www.babbel.com" : "babbel",
                 "lesson nine" : "babbel",
                 "weightwatchers.com" : "weight watchers",
                 "weight watchers" : "weight watchers",
                 "weightwatchers.co" : "weight watchers",
                 "city sports" : "city sports club",
                 "donotpay" : "donotpay",
                 "geico" : "geico",
                 "handy.com" : "handy",
                 "handybook.com" : "handy",
                 "handy" : "handy",
                 "strikingly" : "strikingly",
                 "select protect programme" : "Select & protect",
                 "zoom" : "zoom",
                 "zoom.us" : "zoom",
                 "zoom.com" : "zoom",
                 "zoom" : "zoom",
                 "paymentshield" : "paymentshield",
                 "tailor brands" : "tailor brands",
                 "tailor shaped" : "tailor brands",
                 "tailor toys" : "tailor brands",
                 "scottish equitable" : "scottish equitable",
                 "probiller" : "probiller",
                 "probiller.com" : "probiller",
                 "setapp" : "setapp",
                 "amazonfresh" : "amazon fresh",
                 "prime fresh" : "amazon fresh",
                 "plex" : "plex",
                 "plex.tv" : "plex",
                 "plexinc" : "plex",
                 "plexincpass" : "plex",
                 "experian" : "experian",
                 "creditexpert.co.uk" : "experian",
                 "hulu" : "hulu",
                 "hulu.com" : "hulu",
                 "kahuluikahului" : "hulu",
                 "kahului" : "hulu",
                 "endsleigh" : "endsleigh",
                 "leadpages" : "leadpages",
                 "logmein" : "logmein",
                 "logmein.com" : "logmein",
                 "www.logmein.com" : "logmein",
                 "logmeininc.com" : "logmein",
                 "mealpal" : "mealpal",
                 "mealpal.co.uk" : "mealpal",
                 "mealpalcouk" : "mealpal",
                 "mealpass" : "mealpal",
                 "eharmony.com" : "eharmony",
                 "eharmonycom" : "eharmony",
                 "accountable2you" : "accountable2you",
                 "accountable2you.co" : "accountable2you",
                 "liveplan" : "liveplan",
                 "media com" : "mediacom",
                 "hover" : "hover",
                 "justanswer" : "justanswer",
                 "just answer" : "justanswer",
                 "surveymonkey" : "surveymonkey",
                 "surveymonkey.com" : "surveymonkey",
                 "surveymonkeycore" : "surveymonkeycore",
                 "cosmetics" : "cosmetics",
                 "itcosmetics.co" : "cosmetics",
                 "itcosmeticsdistr" : "cosmetics",
                 "crunchyroll" : "crunchyroll",
                 "bounce energy" : "bounce energy",
                 "bounce" : "bounce energy",
                 "nbc sports" : "nbc sports",
                 "arcadiapower" : "arcadia power",
                 "arcadiapow" : "arcadia power",
                 "arcadia power" : "arcadia power",
                 "close bros" : "close brothers premium finance",
                 "close premium" : "close brothers premium finance",
                 "bodybuilding.com" : "bodybuilding.com",
                 "zoosk" : "zoosk",
                 "showtime" : "showtime",
                 "chicago trib" : "chicago tribune",
                 "chicago concessions" : "chicago tribune",
                 "big cartel" : "big cartel",
                 "prudential" : "prudential",
                 "prudentialdistltd" : "prudential",
                 "care.com" : "care.com",
                 "www.care.com" : "care.com",
                 "mailstrom" : "mailstrom",
                 "mailstrom.co" : "mailstrom",
                 "unite the union" : "unite the union",
                 "tradingview" : "tradingview",
                 "okcupid.co" : "okcupid",
                 "okcupid.com" : "okcupid",
                 "okcupid" : "okcupid",
                 "dominion" : "dominion",
                 "sanebox.com" : "sanebox",
                 "sanebox" : "sanebox",
                 "yesware" : "yesware",
                 "fubotv" : "fubotv",
                 "spire" : "spire",
                 "romwod" : "romwod",
                 "romwod.com" : "romwod",
                 "harvest" : "harvest",
                 "getharvest.com" : "harvest",
                 "dnsimple" : "dnsimple",
                 "avast" : "avast",
                 "put.io" : "put.io",
                 "resumegenius.com" : "resume genius",
                 "centrobill" : "centrobill",
                 "centrobill.com" : "centrobill",
                 "blinkist" : "blinkist",
                 "browserstack" : "browserstack",
                 "browserstack.com" : "browserstack",
                 "zendesk" : "zendesk",
                 "indeed" : "indeed",
                 "indeed.com" : "indeed",
                 "sendgrid" : "sendgrid",
                 "covenant eyes" : "covenant eyes",
                 "state farm" : "state farm",
                 "pluralsight" : "pluralsight",
                 "pluralsight.com" : "pluralsight",
                 "usenetserver" : "usenetserver",
                 "usenetserver.com" : "usenetserver",
                 "fontbundlesnet" : "font bundles",
                 "gyazo" : "gyazo",
                 "gyazo.com" : "gyazo",
                 "workflowy" : "workflowy",
                 "rcn" : "rcn",
                 "dollarshaveclub" : "dollar shave club",
                 "dollar shav" : "dollar shave club",
                 "dollar shave club" : "dollar shave club",
                 "dollar s" : "dollar shave club",
                 "beachbody" : "beachbody",
                 "beachbodycom" : "beachbody",
                 "save the children" : "save the children",
                 "save the child" : "save the children",
                 "getresponse" : "getresponse",
                 "getresponse.com" : "getresponse",
                 "curiositystream" : "curiositystream",
                 "aflac" : "aflac",
                 "hubble contacts" : "hubble contacts",
                 "seehubble.com" : "hubble contacts",
                 "hubble contactshubb" : "hubble contacts",
                 "rebtel" : "rebtel",
                 "svbtle" : "svbtle",
                 "credit karma" : "credit karma",
                 "creditkarma" : "credit karma",
                 "creditkarma.com" : "credit karma",
                 "wp engine" : "wp engine",
                 "wpengine.com" : "wp engine",
                 "dreamhost" : "dreamhost",
                 "dreamhost.com" : "dreamhost",
                 "atlassian" : "atlassian",
                 "south west water" : "south west water",
                 "animal healthcare" : "animal healthcare",
                 "aaptiv" : "aaptiv",
                 "tunnelbear" : "tunnel bear",
                 "tunnel bear" : "tunnel bear",
                 "ring" : "ring",
                 "ring.com" : "ring",
                 "ringcom" : "ring",
                 "freshbooks" : "freshbooks",
                 "mojang" : "mojang",
                 "mojang.com" : "mojang",
                 "tidal" : "tidal",
                 "tidal.com" : "tidal",
                 "www.tidal.com" : "tidal",
                 "resume.io" : "resume.io",
                 "resumeio" : "resume.io",
                 "freelancer" : "freelancer",
                 "freelancer.com" : "freelancer",
                 "www.freelancer.com" : "freelancer",
                 "dreamstime" : "dreamstime",
                 "dreamstime.com" : "dreamstime",
                 "shelter" : "shelter",
                 "shelter.org" : "shelter",
                 "linode" : "linode",
                 "linode.com" : "linode",
                 "docsend" : "docsend",
                 "meetup" : "meetup",
                 "meetup.com" : "meetup",
                 "shipstation" : "shipstation",
                 "marvel" : "marvel",
                 "shudder" : "shudder",
                 "shudder.com" : "shudder",
                 "prezi" : "prezi",
                 "przcharge.prezi.com" : "prezi",
                 "nest" : "nest",
                 "nest.com" : "nest",
                 "cooks illustrated" : "cook's illustrated",
                 "adobe" : "adobe",
                 "adobesyste" : "adobe",
                 "adobesystem" : "adobe",
                 "rescuetime" : "rescuetime",
                 "cloudflare" : "cloudflare",
                 "cloudflare.com" : "cloudflare",
                 "fabletics" : "fabletics",
                 "fabletics.com" : "fabletics",
                 "bench" : "bench",
                 "roosterteeth" : "roosterteeth",
                 "roosterteeth.com" : "roosterteeth",
                 "docusign" : "docusign",
                 "directv" : "directv",
                 "directvgrou" : "directvgrou",
                 "classpass" : "classpass",
                 "classpass.com" : "classpass",
                 "patreon" : "patreon",
                 "patreon.com" : "patreon",
                 "amnesty" : "amnesty",
                 "greenpeace" : "greenpeace",
                 "compassion" : "compassion international",
                 "onlyfans" : "onlyfans",
                 "only fans" : "onlyfans",
                 "onlyfans.com" : "onlyfans",
                 "onlyfanscom" : "onlyfans",
                 "change.org" : "change.org",
                 "changeorg" : "change.org",
                 "sprezzabox" : "sprezzabox",
                 "zwift" : "zwift",
                 "zwift.com" : "zwift",
                 "asana" : "asana",
                 "asana.com" :"asana",
                 "postcodelottery" : "post code lottery",
                 "postcode lottery" : "post code lottery",
                 "yousician" : "yousician",
                 "yousician.com" : "yousician",
                 "roblox" : "roblox",
                 "roblox.com" : "roblox",
                 "canva" : "canva",
                 "canva.com" : "canva",
                 "digital river" : "digital river",
                 "mixmax" : "mixmax",
                 "picmonkey" : "picmonkey",
                 "mbna" : "mbna",
                 "pepco" : "pepco",
                 "potomac" : "potomac",
                 "lynda" : "lynda",
                 "lynda.com" : "lynda",
                 "lyndacominc" : "lynda",
                 "malwarebytes" : "malwarebytes",
                 "malwarebytes.com" : "malwarebytes",
                 "medecins" : "medecins sans frontiers",
                 "debit finance" : "debit finance",
                 "debitfinance.co.uk" : "debit finance",
                 "protonmail" : "protonmail",
                 "xsolla" : "xsolla",
                 "xsolla.com" : "xsolla",
                 "unlocator" : "unlocator",
                 "unlocator.com" : "unlocator",
                 "wework" : "wework",
                 "kissmetrics" : "kissmetrics",
                 "thriva" : "thriva",
                 "thriva.com" : "thriva",
                 "wall street journal" : "the wall street journal",
                 "wall street journa" : "the wall street journal",
                 "wall st journal" : "the wall street journal",
                 "wsj" : "the wall street journal",
                 "harrys" : "harry's",
                 "harry's" : "harry's",
                 "efax" : "efax",
                 "onlinefaxes.com" : "efax",
                 "efax.com" : "efax",
                 "wwe network" : "wwe network",
                 "wwenetwork" : "wwe network",
                 "mailchimp" : "mailchimp",
                 "mailchimp.com" : "mailchimp",
                 "typeform" : "typeform",
                 "expressvpn" : "expressvpn",
                 "expressvpn.com" : "expressvpn",
                 "exprsvpn" : "expressvpn",
                 "cleverbridge" : "cleverbridge",
                 "andrews arnold" : "andrews & arnold",
                 "pocket" : "pocket.com",
                 "codecademy" : "codecademy",
                 "zapier" : "zapier",
                 "zapier.com" : "zapier",
                 "expensify" : "expensify",
                 "expensify.com" : "expensify",
                 "envato" : "envato",
                 "envato.com" : "envato",
                 "envatomarket" : "envato",
                 "lothian buses" : "lothian buses",
                 "blizzard" : "blizzard",
                 "blizzarden" : "blizzard",
                 "vitl" : "vitl",
                 "squarespace" : "squarespace",
                 "scribd" : "scribd",
                 "scribd.com" : "scribd",
                 "vimeo" : "vimeo",
                 "vimeo.com" : "vimeo",
                 "you need a budget" : "you need a budget",
                 "nordvpn" : "nordvpn.com",
                 "grammarly" : "grammarly",
                 "grammarly.com" : "grammarly",
                 "dribble.com" : "dribble",
                 "dribble" : "dribble",
                 "invision" : "invision",
                 "invisionapp" : "invision",
                 "invision.com" : "invision",
                 "invisionapp.com" : "invision",
                 "www.invisionapp.com" : "invision",
                 "www.invision.com" : "invision",
                 "twitter" : "twitter",
                 "stratechery" : "stratechery",
                 "the information" : "the information",
                 "theinformation.com" : "the information",
                 "soundcloud" : "soundcloud",
                 "soundc" : "soundcloud",
                 "busuu" : "busuu",
                 "bandcamp" : "bandcamp",
                 "1password" : "1password",
                 "backblaze" : "backblaze",
                 "backblazeback" : "backblaze",
                 "gocardless" : "gocardless",
                 "emac" : "emac",
                 "xero" : "xero",
                 "xero.com" : "xero",
                 "ford" : "ford",
                 "ancestry" : "ancestry",
                 "ancestry.com" : "ancestry",
                 "ancestrycom" : "ancestry",
                 "ccbill" : "ccbill",
                 "ccbill.com" : "ccbill",
                 "wix" : "wix",
                 "wix.com" : "wix",
                 "denplan" : "denplan",
                 "boots rewardscheme" : "boots reward scheme",
                 "boots reward scheme" : "boots reward scheme",
                 "boots opt" : "boots reward scheme",
                 "bmw" : "bmw",
                 "webbmw" : "webbmw",
                 "bmwfinancial" : "bmwfinancial",
                 "github" : "github",
                 "github.com" : "github",
                 "dvla" : "dvla",
                 "Strava" : "strava",
                 "stravacom" : "strava",
                 "shopify" : "shopify",
                 "shopifycomc" : "shopify",
                 "shopifyco" : "shopify",
                 "dropbox" : "dropbox",
                 "dropboxinte" : "dropbox",
                 "dropboxint" : "dropbox",
                 "jetbrains" : "jetbrains",
                 "jetbrains.com" : "jetbrains",
                 "evernote" : "evernote",
                 "evernotecor" : "evernote",
                 "evernote.com" : "evernote",
                 "skype" : "skype",
                 "skype.com" : "skype",
                 "go.skype.com" : "skype",
                 "heroku" : "heroku",
                 "www.herokucharge.com" : "heroku",
                 "herokucharge.com" : "heroku",
                 "medium" : "medium",
                 "medium.com" : "medium",
                 "digitalocean.com" : "digitalocean",
                 "digitalocean" : "digitalocean",
                 "pandora" : "pandora",
                 "fastspring" : "fastspring",
                 "fastspring.com" : "fastspring",
                 "fastspringsoftware.com" : "fastspring",
                 "lastpass.com" : "lastpass",
                 "lastpass" : "lastpass",
                 "hostgator" : "hostgator",
                 "hostgator.com" : "hostgator",
                 "oxfam" : "oxfam",
                 "playstationnetwork" : "playstation network",
                 "playstation" : "playstation network",
                 "playstatio" : "playstation network",
                 "namecheap" : "namecheap",
                 "name cheap" : "namecheap",
                 "namecheap.com" : "namecheap",
                 "name-cheap.com" : "namecheap",
                 "linkedin" : "linkedin",
                 "linkedin.com" : "linkedin",
                 "gohenry" : "gohenry",
                 "udemy" : "udemy",
                 "udemy.com" : "udemy",
                 "monzome" : "monzo",
                 "monzo" : "monzo",
                 "headspace" : "headspace",
                 "headspace.com" : "headspace",
                 "paypal" : "paypal",
                 "revolut" : "revolut",
                 "revolut.com" : "revolut",
                 "wired" : "wired",
                 "shopwired" : "wired",
                 "wiredin" : "wired",
                 "disneylife" : "disney",
                 "deezer" : "deezer",
                 "deezermusic" : "deezermusic",
                 "apple music" : "apple",
                 "apple" : "apple",
                 "itunes" : "apple",
                 "lycamobile" : "lycamobile",
                 "lycamobile.com" : "lycamobile",
                 "pink parcel" : "pink parcel",
                 "flavourly" : "flavourly",
                 "pact coffee" : "pact coffee",
                 "wwwpactcoffeecom" : "pact coffee",
                 "pactcoffee.com" : "pact coffee",
                 "www.pactcoffee.com" : "pact coffee",
                 "simplycook" : "simply cook",
                 "simply cook" : "simply cook",
                 "riverford" : "riverford",
                 "riverford.co.uk" : "riverford",
                 "riverford.co.u" : "riverford",
                 "riverford.c" : "riverford",
                 "mindful chef" : "mindful chef",
                 "telegraph" : "telegraph",
                 "cornerstone" : "cornerstone",
                 "birchbox" : "birchbox",
                 "netflix" : "netflix",
                 "netflix.com" : "netflix",
                 "netflix.co" : "netflix",
                 "the week" : "the week",
                 "talktalk" : "talktalk",
                 "guardian" : "the guardian",
                 "guardiannewsandmedia" : "the guardian",
                 "glossybox" : "glossybox",
                 "glossybox.com" : "glossybox",
                 "graze" : "graze",
                 "graze.com" : "graze",
                 "grazecom" : "graze",
                 "amazon" : "amazon",
                 "economist" : "the economist",
                 "theeconomist" : "the economist",
                 "vonage" : "vonage",
                 "vonage.com" : "vonage",
                 "virgin mobile" : "virgin mobile",
                 "times" : "the times",
                 "hellofresh" : "hellofresh",
                 "hellofresh.com" : "hellofresh",
                 "xbox" : "xbox",
                 "xboxlive" : "xboxlive",
                 "xboxliv" : "xboxlive",
                 "amazonprime" : "amazon",
                 "amzn" : "amazon",
                 "financial times" : "financial times",
                 "ft.com" : "financial times",
                 "ee" : "ee",
                 "impark" : "impark",
                 "rac" : "the rac",
                 "rac.com" : "the rac",
                 "rac.co.uk" : "the rac",
                 "gasbuddy" : "gasbuddy",
                 "limebike" : "limebike",
                 "lime" : "limebike",
                 "lim" : "limebike",
                 "limeuk" : "limebike",
                 "lime bike" : "limebike",
                 "carmax" : "carmax",
                 "green flag" : "green flag",
                 "greenflag" : "green flag",
                 "zipcar" : "zipcar",
                 "zipcar.com" : "zipcar",
                 "parkmobile" : "parkmobile",
                 "parkmobile.com" : "parkmobile",
                 "park mobile" : "parkmobile",
                 "lyft" : "lyft",
                 "uber" : "uber",
                 "uber.com" : "uber",
                 "help.uber.com" : "uber",
                 "affinity water" : "affinity water",
                 "battlbox" : "battlbox",
                 "privacy" : "privacy",
                 "privacy.com" : "privacy",
                 "convertkit.com" : "convert kit",
                 "bespoke" : "bespoke post",
                 "groovebook" : "groovebook",
                 "gumroad" : "gumroad",
                 "footprint" : "footprint",
                 "cricket" : "cricket wireless",
                 "avalon" : "avalon",
                 "function of beauty" : "function of beauty",
                 "function of beaut" : "function of beauty",
                 "zulily" : "zulily",
                 "sams club" : "sam's club",
                 "sams" : "sam's club",
                 "samsclub" : "sam's club",
                 "feedly" : "feedly",
                 "feedly.com" : "feedly",
                 "emeals" : "emeals",
                 "square enix" : "square enix",
                 "square eni" : "square enix",
                 "musicnotes" : "musicnotes",
                 "musicnotes.com" : "musicnotes",
                 "walmart" : "walmart",
                 "walmart.com" : "walmart",
                 "wal mart" : "walmart",
                 "wm" : "walmart",
                 "shutterstock" : "shutterstock",
                 "shutterstock.com" : "shutterstock",
                 "shutterstock.c" : "shutterstock",
                 "qvc" : "qvc",
                 "qvcuk.com" : "qvcuk.com",
                 "qvcus.com" : "qvcus.com",
                 "qvc.com" : "qvc",
                 "etsy" : "etsy",
                 "etsy.com" : "etsy",
                 "kickstarter" : "kickstarter",
                 "kickstarter.com" : "kickstarter",
                 "loot crate" : "loot crate",
                 "loot c353" : "loot crate",
                 "Lootcratein" : "loot crate",
                 "bespoke" : "bespoke post",
                 "bespokenew" : "bespoke post",
                 "footprint" : "footprint",
                 "mcafee" : "mcafee",
                 "iconfinder" : "iconfinder",
                 "iconfinder.com" : "iconfinder",
                 "healthy pet club" : "healthy pet club",
                 "u haul" : "u-haul",
                 "meundies" : "meundies",
                 "meundies.com" : "meundies",
                 "justfab" : "justfab",
                 "justfab.com" : "justfab",
                 "justfabulou" : "justfab",
                 "msbill.info" : "microsoft",
                 "aarons" : "aaron's",
                 "aaron's" : "aaron's",
                 "convertkit.com" : "convertkit",
                 "convertkit" : "convertkit.com",
                 "kohl's" : "kohl's",
                 "kohls" : "kohl's",
                 "kohls.com" : "kohl's",
                 "chaturbill" : "chaturbill",
                 "nfl" : "nfl",
                 "mercari" : "mercari",
                 "shutterfly" : "shutterfly",
                 "barnes noble" : "barnes & noble",
                 "barnes nob" : "barnes & noble",
                 "barnes" : "barnes & noble",
                 "macys" : "macys",
                 "macy's" : "macys",
                 "macy" : "macys",
                 "intercom" : "intercom",
                 "intercom.io" : "intercom",
                 "sephora" : "sephora",
                 "target" : "target",
                 "best buy" : "best buy",
                 "ebay" : "ebay",
                 "ebay.com" : "ebay",
                 "ebaycharity" : "ebay",
                 "ebaycharit" : "ebay",
                 "visa direct" : "visa direct",
                 "Us Bank National" : "Us Bank National",
                 "atm" : "atm transaction",
                 "parkside" : "parkside apartments",
                 "juan water bea" : "san juan water and beach",
                 "mediacom" : "mediacom",
                 "tikgames" : "tikgames",
                 "TikGames" : "tikgames",
                 "connecticare" : "connecticare",
                 "thrive" : "thrive",
                 "neon" : "neon",
                 "grow credit" : "grow credit",
                 "wellstar" : "wellstar",
                 "instore group" : "instore group",
                 "fdm associates" : "fdm associates"
                }
